### ISSUE TITLE
OSError: Cannot run program "pjf" 

### ISSUE THREAD

**Issue by fyoorer** [mseclab/Burp-PyJFuzz#1]
I am running the Burp-PyJFuzz extention on latest Burpsuite Pro on Mac OS X.
pjf is installed and working perfectly on the command-line.

Getting this error in the extention's Error tab:

`Traceback (most recent call last):
  File "/Users/aditya/Documents/Tools/Burp-PyJFuzz/burp-pyjfuzz.py", line 187, in getNextPayload
    payload = self.fuzz(payload)
  File "/Users/aditya/Documents/Tools/Burp-PyJFuzz/burp-pyjfuzz.py", line 196, in fuzz
    p1 = subprocess.Popen([self.pyjfuzz, '--J', '%s' % original_payload] + self._args, stdout=subprocess.PIPE)
  File "/Users/aditya/Downloads/jython-standalone-2.7.0.jar/Lib/subprocess.py", line 830, in __init__
  File "/Users/aditya/Downloads/jython-standalone-2.7.0.jar/Lib/subprocess.py", line 1352, in _execute_child
OSError: Cannot run program "pjf" (in directory "/Users/aditya/Documents/Tools/Burp-PyJFuzz"): error=2, No such file or directory
	at org.python.core.PyException.doRaise(PyException.java:226)
	at org.python.core.Py.makeException(Py.java:1337)
	at org.python.core.Py.makeException(Py.java:1341)
	at org.python.core.Py.makeException(Py.java:1345)
	at subprocess$py._execute_child$39(/Users/aditya/Downloads/jython-standalone-2.7.0.jar/Lib/subprocess.py:1354)
	at subprocess$py.call_function(/Users/aditya/Downloads/jython-standalone-2.7.0.jar/Lib/subprocess.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at subprocess$py.__init__$21(/Users/aditya/Downloads/jython-standalone-2.7.0.jar/Lib/subprocess.py:912)
	at subprocess$py.call_function(/Users/aditya/Downloads/jython-standalone-2.7.0.jar/Lib/subprocess.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:394)
	at org.python.pycode._pyx4.fuzz$15(/Users/aditya/Documents/Tools/Burp-PyJFuzz/burp-pyjfuzz.py:200)
	at org.python.pycode._pyx4.call_function(/Users/aditya/Documents/Tools/Burp-PyJFuzz/burp-pyjfuzz.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx4.getNextPayload$12(/Users/aditya/Documents/Tools/Burp-PyJFuzz/burp-pyjfuzz.py:188)
	at org.python.pycode._pyx4.call_function(/Users/aditya/Documents/Tools/Burp-PyJFuzz/burp-pyjfuzz.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$JSONFuzzer$9.getNextPayload(Unknown Source)
	at burp.wd.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by dzonerzy** [comment]
Hi fyoorer,

Thank you for your interest in PyJFuzz, the issue should be solved now! Please give it a shot and let me know.

Best regards,
Daniele Linguaglossa

**Comment by fyoorer** [comment]
Thanks @dzonerzy
